services:
  - type: web
    name: ai-paper-aggregator
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python server.py"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: MY_EMAIL
        sync: false
      - key: APP_PASSWORD
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: FROM_EMAIL
        sync: false

