
services:
  db:
    image: pgvector/pgvector:pg17
    container_name: paper_aggregator_db
    restart: always
    environment:
      POSTGRES_USER: aggregator_user
      POSTGRES_PASSWORD: super_secure_password123
      POSTGRES_DB: research_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: